### ISSUE TITLE
Dip Switches

### ISSUE THREAD

**Issue by HoldenWright** [cjoshmartin/elevator-simulation#12]
# switches
Switch 1 takes priority over switch 8.  
## Users Stories
- [x] **Switch 1** allows the user to enter elevator private mode.
-  If **switch 1** goes high, the elevator will freeze at the currently location. the elevator is locked has no functionality until switch 1 goes low (the elevator returns back to its previous function).
- [ ] **Switch 8** is meant to represent the secret mode mechanism. 
-  If **switch 8** is high, the user should be prompt to enter in their two digit user ID and a security code. 
 - Upon the correct password, the elevator should go to floor zero (the secret floor) when the push button is pressed. 
- [ ] When the user wants to leave secret mode, switch 8 must go from high to low followed by a press of the push button. The elevator must then return to floor one. 
- [x] If switch 8 and switch 1 are both low, the elevator should work normally.

**Comment by cjoshmartin** [comment]
#13 need to freeze the current floor in the leds
