### ISSUE TITLE
potentiometer

### ISSUE THREAD

**Issue by HoldenWright** [cjoshmartin/elevator-simulation#8]
Potentiometer:The potentiometer controls the opening and closing of the elevator door. If the potentiometer is turned all the way to the left, the elevator door should open. If the potentiometer is turned all the way to the right, the elevator door should close. The DC motor simulating the elevator door should spin accordingly. If the potentiometer is turned to a position other than the max right or max left, the elevator door should do nothing.

**Comment by cjoshmartin** [comment]
DC Motor: The DC motor is meant to replicate the opening and closing of the elevator door. The DC motor should spin at a 100% duty cycle when opening the elevator door and should spin at a 50% duty cycle when closing the elevator door. The elevator door should be able to open and close at any time other than when the elevator is in motion or in private mode. The elevator door should take approximately 4 seconds to close and 2 seconds to open.
